const logs = [
  {
    symbol: "AAPL",
    company: "Apple Inc.",
    price: "1.03 USD",
    status: "Received",
    date: "8/7/2025 - 09:28",
    amount: "35",
    icon: "sold-icon.png",
  },
  {
    symbol: "TSLA",
    company: "Tesla Inc.",
    price: "2.50 USD",
    status: "Sell",
    date: "8/6/2025 - 14:45",
    amount: "12",
    icon: "sold-icon.png",
  },
  {
    symbol: "GOOGL",
    company: "Alphabet Inc.",
    price: "3.15 USD",
    status: "Received",
    date: "8/5/2025 - 11:02",
    amount: "22",
    icon: "sold-icon.png",
  },
  {
    symbol: "MSFT",
    company: "Microsoft Corp.",
    price: "1.87 USD",
    status: "Sell",
    date: "8/5/2025 - 13:17",
    amount: "18",
    icon: "sold-icon.png",
  },
  {
    symbol: "AMZN",
    company: "Amazon.com Inc.",
    price: "2.99 USD",
    status: "Received",
    date: "8/4/2025 - 10:30",
    amount: "40",
    icon: "sold-icon.png",
  },
  {
    symbol: "NFLX",
    company: "Netflix Inc.",
    price: "1.25 USD",
    status: "Sell",
    date: "8/3/2025 - 16:50",
    amount: "27",
    icon: "sold-icon.png",
  },
  {
    symbol: "NVDA",
    company: "NVIDIA Corp.",
    price: "3.80 USD",
    status: "Received",
    date: "8/2/2025 - 09:00",
    amount: "14",
    icon: "sold-icon.png",
  },
  {
    symbol: "META",
    company: "Meta Platforms Inc.",
    price: "1.65 USD",
    status: "Sell",
    date: "8/1/2025 - 15:20",
    amount: "30",
    icon: "sold-icon.png",
  },
  {
    symbol: "INTC",
    company: "Intel Corp.",
    price: "0.90 USD",
    status: "Received",
    date: "7/31/2025 - 12:10",
    amount: "50",
    icon: "sold-icon.png",
  },
  {
    symbol: "BABA",
    company: "Alibaba Group",
    price: "1.40 USD",
    status: "Sell",
    date: "7/30/2025 - 08:45",
    amount: "20",
    icon: "sold-icon.png",
  },
];

export default logs
